# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      JetBrains Mono
font_size 13.0

#: }}}

#: Text cursor customization {{{

cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval -1

cursor_trail 100
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

#: }}}

#: Scrollback {{{

scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

#: }}}

#: Mouse {{{

url_color #0087bd
url_style curly
detect_urls yes
focus_follows_mouse no
copy_on_select no
paste_actions quote-urls-at-prompt,confirm

#: }}}

#: Window layout {{{

active_border_color #00ff00
inactive_border_color #cccccc
bell_border_color #ff5a00

hide_window_decorations no

#: }}}

#: Performance tuning {{{

repaint_delay 10
input_delay 3
sync_to_monitor yes

#: }}}

#: Terminal bell {{{

enable_audio_bell yes
visual_bell_duration 0.0
window_alert_on_bell yes

#: }}}

#: Keyboard shortcuts {{{

# Switch tabs with Command + number
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
